FROM apache/spark:3.5.0-python3
USER root

# Install MySQL JDBC driver for Day 13 (JDBC reads from MySQL)
RUN wget -P /opt/spark/jars https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/8.0.33/mysql-connector-j-8.0.33.jar

# Switch back to spark user
USER ${spark_uid:-185}
WORKDIR /opt/spark/work-dir